/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSimulacionRouteImport } from './routes/_authenticated/simulacion'
import { Route as AuthenticatedEnVivoRouteImport } from './routes/_authenticated/en-vivo'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedColapsoRouteImport } from './routes/_authenticated/colapso'
import { Route as AuthenticatedAeropuertosRouteImport } from './routes/_authenticated/aeropuertos'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSimulacionRoute = AuthenticatedSimulacionRouteImport.update({
  id: '/simulacion',
  path: '/simulacion',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEnVivoRoute = AuthenticatedEnVivoRouteImport.update({
  id: '/en-vivo',
  path: '/en-vivo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedColapsoRoute = AuthenticatedColapsoRouteImport.update({
  id: '/colapso',
  path: '/colapso',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAeropuertosRoute =
  AuthenticatedAeropuertosRouteImport.update({
    id: '/aeropuertos',
    path: '/aeropuertos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/aeropuertos': typeof AuthenticatedAeropuertosRoute
  '/colapso': typeof AuthenticatedColapsoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/en-vivo': typeof AuthenticatedEnVivoRoute
  '/simulacion': typeof AuthenticatedSimulacionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/aeropuertos': typeof AuthenticatedAeropuertosRoute
  '/colapso': typeof AuthenticatedColapsoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/en-vivo': typeof AuthenticatedEnVivoRoute
  '/simulacion': typeof AuthenticatedSimulacionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/register': typeof RegisterRoute
  '/_authenticated/aeropuertos': typeof AuthenticatedAeropuertosRoute
  '/_authenticated/colapso': typeof AuthenticatedColapsoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/en-vivo': typeof AuthenticatedEnVivoRoute
  '/_authenticated/simulacion': typeof AuthenticatedSimulacionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/aeropuertos'
    | '/colapso'
    | '/dashboard'
    | '/en-vivo'
    | '/simulacion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/aeropuertos'
    | '/colapso'
    | '/dashboard'
    | '/en-vivo'
    | '/simulacion'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/register'
    | '/_authenticated/aeropuertos'
    | '/_authenticated/colapso'
    | '/_authenticated/dashboard'
    | '/_authenticated/en-vivo'
    | '/_authenticated/simulacion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/simulacion': {
      id: '/_authenticated/simulacion'
      path: '/simulacion'
      fullPath: '/simulacion'
      preLoaderRoute: typeof AuthenticatedSimulacionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/en-vivo': {
      id: '/_authenticated/en-vivo'
      path: '/en-vivo'
      fullPath: '/en-vivo'
      preLoaderRoute: typeof AuthenticatedEnVivoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/colapso': {
      id: '/_authenticated/colapso'
      path: '/colapso'
      fullPath: '/colapso'
      preLoaderRoute: typeof AuthenticatedColapsoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/aeropuertos': {
      id: '/_authenticated/aeropuertos'
      path: '/aeropuertos'
      fullPath: '/aeropuertos'
      preLoaderRoute: typeof AuthenticatedAeropuertosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAeropuertosRoute: typeof AuthenticatedAeropuertosRoute
  AuthenticatedColapsoRoute: typeof AuthenticatedColapsoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEnVivoRoute: typeof AuthenticatedEnVivoRoute
  AuthenticatedSimulacionRoute: typeof AuthenticatedSimulacionRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAeropuertosRoute: AuthenticatedAeropuertosRoute,
  AuthenticatedColapsoRoute: AuthenticatedColapsoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEnVivoRoute: AuthenticatedEnVivoRoute,
  AuthenticatedSimulacionRoute: AuthenticatedSimulacionRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
